### ISSUE TITLE
Development Task List 

### ISSUE THREAD

**Issue by dnolter959** [dnolter959/longdrop2#1]
### Core Functionality-Related
- [x] Handle dependencies
- [x] Figure out warnings in lme4 runs
- [x] Generalize:
  - [x] generate_design_X_full
  - [x] generate_complete_dataset_using_multiple_imputation

### User Experience Improvements
- [x] Speed things up?  
- [x] Make `longdrop` a class and store useful info in associated `str` object
- [x] override `plot` for longdrop `object`
- [x] Is there a way to avoid passing `time_var`?
- [ ] Add more plots and more granular control over what is plotted

### Documentation-Related
- [x] add documentation
- [ ] add tests
- [x] improve README example and write-up

### Fixes
- [x] Handling random intercepts and slopes or just intercepts
